### ISSUE TITLE
Bluetoothaudiofix

### ISSUE THREAD

**Issue by Mocar2D** [Martinz64/AliucordRN-Plugins#1]
Is there any idea of when the plugin could be ported to aliucord rn? Because well its not opimal to listen to potato quality lol

**Comment by Martinz64** [comment]
the plugin is already there: https://github.com/Martinz64/AliucordRN-Plugins/raw/builds/BluetoothAudioFix.zip

**Comment by Mocar2D** [comment]
Indeed it was lol that's why i closed it almost instantly because some braincells decided to work, mind putting it in the aliucord rn plugins readme? :3
